// The tutorial's anti-rot guarantee (SPEC §16): the whole arc, headless. This suite drives
// the EXACT functions the page calls — site/lessons.mjs `buildArc(loam)` over the browser
// barrel — through all eleven lessons IN ORDER, asserting every check green, that no check is
// vacuously green before its lesson runs, that a revisit (reboot from the same origin)
// re-verifies every green from the ground alone, and the finale's whole claim: export →
// `loam init --seed` → `loam pull` → the served store answers `_hex` for `_hex`.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeAll, describe, expect, it, vi } from "vitest";
import * as loam from "../../src/browser/index.js";
import { run } from "../../src/cli/cli.js";
import { storePath } from "../../src/cli/config.js";
import { SqliteBackend } from "../../src/store/sqlite.js";
import { Gateway } from "../../src/gateway/gateway.js";
import { MemStorage } from "../store/mem-storage.js";
// The page and this test share one arc — that identity IS the anti-rot guarantee.
import {
  FILM,
  bootTutorialStore,
  buildArc,
  buildExport,
  type LessonCtx,
} from "../../site/lessons.mjs";

vi.setConfig({ testTimeout: 20000 });

const packetFile = (name: string): unknown[] =>
  (
    JSON.parse(readFileSync(join(process.cwd(), "site", "packets", name), "utf8")) as {
      deltas: unknown[];
    }
  ).deltas;

let clock = 1_753_000_000_000;
const nextTs = (): number => ++clock;

async function makeCtx(storage: MemStorage): Promise<LessonCtx> {
  const { gateway, seed, author } = await bootTutorialStore(loam, storage);
  return {
    gateway,
    storage,
    seed,
    author,
    packets: { circle: packetFile("circle.json"), adversary: packetFile("adversary.json") },
    ts: nextTs,
  };
}

beforeAll(() => {
  // The packets are committed data, regenerated byte-identically — a drifted generator or a
  // hand-edited packet fails here before any lesson gets to be confused by it.
  execFileSync(process.execPath, [join("scripts", "gen-packets.mjs"), "--check"], {
    cwd: process.cwd(),
    stdio: "pipe",
  });
});

describe("the tutorial arc, headless", () => {
  it("runs all eleven lessons in order; every check earns its green", async () => {
    const storage = new MemStorage();
    const ctx = await makeCtx(storage);
    const arc = buildArc(loam);
    expect(arc).toHaveLength(11);

    for (const lesson of arc) {
      // No lesson may be green before it runs — a vacuous check teaches nothing and can lie.
      // (Lessons 1 and 11 are read-only by design: boot performed 1; 11 IS the export.)
      if (lesson.id !== 1 && lesson.id !== 11) {
        expect(await lesson.check(ctx), `lesson ${lesson.id} green before it ran`).toBe(false);
      }
      // The moment between lessons 2 and 3, pinned: the fact is real before any schema is.
      if (lesson.id === 3) {
        await expect(ctx.gateway.query(`{ film(entity: "${FILM}") { title } }`)).rejects.toThrow(
          /nothing is registered/,
        );
      }
      // Before lesson 10, the stranger at the window sees a store with nothing public.
      if (lesson.id === 10) {
        await expect(
          ctx.gateway.queryPublic(`{ film(entity: "${FILM}") { title } }`),
        ).rejects.toThrow(loam.NothingPublic);
      }
      await lesson.perform(ctx);
      expect(await lesson.check(ctx), `lesson ${lesson.id} (${lesson.title})`).toBe(true);
    }

    // The adversary's forgery is still in the ground after lesson 7's defense — visible,
    // preserved, and refusing to matter (the lesson's check asserted the defended title).
    const forged = ctx.packets.adversary[0] as { id: string };
    expect(ctx.gateway.offeredDeltas().some((d) => d.id === forged.id)).toBe(true);

    await ctx.gateway.close();

    // THE REVISIT: reboot from the same origin — progress is the store, so every lesson
    // re-verifies green from the ground alone, no memory anywhere else.
    const again = await makeCtx(storage);
    for (const lesson of buildArc(loam)) {
      expect(await lesson.check(again), `lesson ${lesson.id} after revisit`).toBe(true);
    }
    await again.gateway.close();
  });

  it("the finale keeps its whole promise: export → init --seed → pull → _hex for _hex", async () => {
    const storage = new MemStorage();
    const ctx = await makeCtx(storage);
    for (const lesson of buildArc(loam)) {
      await lesson.perform(ctx);
    }
    const inTab = await ctx.gateway.query(`{ film(entity: "${FILM}") { title _hex } }`);
    const tabView = inTab.data as { film: { title: string; _hex: string } };
    expect(tabView.film.title).toBe("Arrival");

    const dir = mkdtempSync(join(tmpdir(), "loam-tutorial-"));
    const io = { out: () => {}, err: (s: string) => console.error(s) };
    try {
      const file = join(dir, "my-store.json");
      writeFileSync(file, buildExport(loam, ctx));
      const exported = JSON.parse(readFileSync(file, "utf8")) as { seed: string };

      expect(await run(["init", "--home", dir, "--seed", exported.seed], io)).toBe(0);
      expect(await run(["pull", file, "--home", dir], io)).toBe(0);

      const laptop = await Gateway.open(new SqliteBackend(storePath(dir)), {
        seed: exported.seed,
      });
      const answer = await laptop.query(`{ film(entity: "${FILM}") { title _hex } }`);
      const laptopView = answer.data as { film: { title: string; _hex: string } };
      // Not a copy that resembles it: THE SAME STORE, proven by content address.
      expect(laptopView.film.title).toBe("Arrival");
      expect(laptopView.film._hex).toBe(tabView.film._hex);
      await laptop.close();
    } finally {
      await ctx.gateway.close();
      rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    }
  });
});
