// The tutorial's anti-rot guarantee (SPEC §16): the whole arc, headless. This suite drives
// the EXACT functions the page calls — site/lessons.mjs `buildArc(loam)` over the browser
// barrel — through all eleven lessons IN ORDER, asserting every check green, that no check is
// vacuously green before its lesson runs, that a revisit (reboot from the same origin)
// re-verifies every green from the ground alone, and the finale's whole claim: export →
// `loam init --seed` → `loam pull` → the served store answers `_hex` for `_hex`.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { beforeAll, describe, expect, it, vi } from "vitest";
import * as loam from "../../src/browser/index.js";
import { run } from "../../src/cli/cli.js";
import { storePath } from "../../src/cli/config.js";
import { SqliteBackend } from "../../src/store/sqlite.js";
import { Gateway } from "../../src/gateway/gateway.js";
import { MemStorage } from "../store/mem-storage.js";
// The page and this test share one arc — that identity IS the anti-rot guarantee.
import {
  FILM,
  bootTutorialStore,
  buildArc,
  buildExport,
  recordHomecoming,
  type LessonCtx,
} from "../../demos/tutorial/lessons.mjs";

vi.setConfig({ testTimeout: 20000 });

const packetFile = (name: string): unknown[] =>
  (
    JSON.parse(readFileSync(join(process.cwd(), "demos", "tutorial", "packets", name), "utf8")) as {
      deltas: unknown[];
    }
  ).deltas;

let clock = 1_753_000_000_000;
const nextTs = (): number => ++clock;

async function makeCtx(storage: MemStorage): Promise<LessonCtx> {
  const { gateway, seed, author } = await bootTutorialStore(loam, storage);
  return {
    gateway,
    storage,
    seed,
    author,
    packets: { circle: packetFile("circle.json"), adversary: packetFile("adversary.json") },
    ts: nextTs,
  };
}

beforeAll(() => {
  // The packets are committed data, regenerated byte-identically — a drifted generator or a
  // hand-edited packet fails here before any lesson gets to be confused by it.
  execFileSync(process.execPath, [join("scripts", "gen-packets.mjs"), "--check"], {
    cwd: process.cwd(),
    stdio: "pipe",
  });
});

describe("the tutorial arc, headless", () => {
  it("runs all twelve lessons in order; every check earns its green", async () => {
    const storage = new MemStorage();
    const ctx = await makeCtx(storage);
    const arc = buildArc(loam);
    expect(arc).toHaveLength(12);

    for (const lesson of arc) {
      // No lesson may be green before it runs — a vacuous check teaches nothing and can lie.
      // (Lesson 1 is exempt: boot itself performed it, and the check still reads the ground.)
      if (lesson.id !== 1) {
        expect(await lesson.check(ctx), `lesson ${lesson.id} green before it ran`).toBe(false);
      }
      // Before lesson 2 registers anything, the store has no queryable surface at all — a fact
      // can be real before any schema is (the reveal lesson 5 makes explicit).
      if (lesson.id === 2) {
        await expect(ctx.gateway.query(`{ film(entity: "${FILM}") { title } }`)).rejects.toThrow(
          /nothing is registered/,
        );
      }
      // Before lesson 11, the stranger at the window sees a store with nothing public.
      if (lesson.id === 11) {
        await expect(
          ctx.gateway.queryPublic(`{ film(entity: "${FILM}") { title } }`),
        ).rejects.toThrow(loam.NothingPublic);
      }
      await lesson.perform(ctx);
      if (lesson.id === 12) {
        // The finale's green is earned OUTSIDE the tab: perform alone must not grant it. The
        // page records the homecoming after a verified localhost match (the honest path is
        // driven whole by the second test); here we take the side door the copy celebrates —
        // the record itself is the check's subject, and it reads back from the ground.
        expect(await lesson.check(ctx), "lesson 12 green without a homecoming").toBe(false);
        await recordHomecoming(loam, ctx, "side-door");
      }
      expect(await lesson.check(ctx), `lesson ${lesson.id} (${lesson.title})`).toBe(true);

      // The reveal at the heart of Act II, pinned: after lesson 5 writes Alice with the pen but
      // before lesson 6 evolves the lens, the Film view has no `guests` field at all — a lens
      // shows only what it gathers. This stops being true the moment lesson 6 runs, so it can
      // only be an in-order pin, never a durable check.
      if (lesson.id === 5) {
        const res = await ctx.gateway.query(`{ film(entity: "${FILM}") { guests } }`);
        expect(
          (res.errors ?? []).join(" "),
          "guests must be an unknown field before lesson 6",
        ).toMatch(/guests/);
      }
    }

    // The adversary's forgery is still in the ground after lesson 8's defense — visible,
    // preserved, and refusing to matter (the lesson's check asserted the defended title).
    const forged = ctx.packets.adversary[0] as { id: string };
    expect(ctx.gateway.offeredDeltas().some((d) => d.id === forged.id)).toBe(true);

    await ctx.gateway.close();

    // THE REVISIT: reboot from the same origin — progress is the store, so every lesson
    // re-verifies green from the ground alone, no memory anywhere else.
    const again = await makeCtx(storage);
    for (const lesson of buildArc(loam)) {
      expect(await lesson.check(again), `lesson ${lesson.id} after revisit`).toBe(true);
    }
    await again.gateway.close();
  });

  it("the finale keeps its whole promise: export → init --seed → pull → _hex for _hex", async () => {
    const storage = new MemStorage();
    const ctx = await makeCtx(storage);
    for (const lesson of buildArc(loam)) {
      await lesson.perform(ctx);
    }
    const inTab = await ctx.gateway.query(`{ film(entity: "${FILM}") { title _hex } }`);
    const tabView = inTab.data as { film: { title: string; _hex: string } };
    expect(tabView.film.title).toBe("Arrival");

    const dir = mkdtempSync(join(tmpdir(), "loam-tutorial-"));
    const io = { out: () => {}, err: (s: string) => console.error(s) };
    try {
      const file = join(dir, "my-store.json");
      writeFileSync(file, buildExport(loam, ctx));
      const exported = JSON.parse(readFileSync(file, "utf8")) as { seed: string };

      expect(await run(["init", "--home", dir, "--seed", exported.seed], io)).toBe(0);
      expect(await run(["pull", file, "--home", dir], io)).toBe(0);

      const laptop = await Gateway.open(new SqliteBackend(storePath(dir)), {
        seed: exported.seed,
      });
      const answer = await laptop.query(`{ film(entity: "${FILM}") { title _hex } }`);
      const laptopView = answer.data as { film: { title: string; _hex: string } };
      // Not a copy that resembles it: THE SAME STORE, proven by content address.
      expect(laptopView.film.title).toBe("Arrival");
      expect(laptopView.film._hex).toBe(tabView.film._hex);
      await laptop.close();

      // The honest homecoming: the match verified, the page records it, and lesson 12's
      // check reads it back from the ground — progress is the store, all the way to the end.
      const finale = buildArc(loam).find((l) => l.id === 12)!;
      expect(await finale.check(ctx)).toBe(false);
      await recordHomecoming(loam, ctx, laptopView.film._hex);
      expect(await finale.check(ctx)).toBe(true);
    } finally {
      await ctx.gateway.close();
      rmSync(dir, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    }
  });
});
